# Generated by Django 6.0.7 on 2026-08-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_address_latitude_address_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
    ]
