# Generated by Django 6.0.7 on 2026-07-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.CharField(max_length=30),
        ),
    ]
