# Generated by Django 6.0.7 on 2026-08-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_original_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="original_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
