# Generated by Django 6.0.7 on 2026-08-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_productreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
