# Generated by Django 6.0.7 on 2026-08-14 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_product_stock"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="productreview",
            name="unique_product_review_per_user",
        ),
        migrations.DeleteModel(
            name="ProductReview",
        ),
    ]
